######################################################################
# Automatically generated by qmake (3.0) jue. ago. 14 09:43:30 2014
######################################################################

TEMPLATE = app
TARGET = findfiles
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
