######################################################################
# Automatically generated by qmake (3.0) jue. ago. 14 23:52:26 2014
######################################################################

TEMPLATE = app
TARGET = menu
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
